# Generated by Django 5.2.4 on 2025-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
